BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

%labels
  AUTHOR nicolas.soirat@etu.umontpellier.fr

%post
  echo "Updating CentOS and installing mandatory packages"
  yum -y update 
  yum group install -y "development tools"
  yum -y install  wget git zlib-devel which 
  #Pour Python 3.6.5  
  yum install -y bzip2-devel ncurses-devel readline-devel tk-devel gdbm-devel xz-devel expat-devel 

  echo "Installing the lastest release of Python"
  wget http://python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
  tar xf Python-3.6.3.tar.xz
  cd Python-3.6.3
  ./configure --prefix=/usr/local --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
  make && make altinstall

  echo "Insalling BCFtools"
  git clone git://github.com/samtools/htslib.git
  git clone git://github.com/samtools/bcftools.git
  cd bcftools 
  make
  mv bcftools /usr/local/bin
  cd ..
  rm -rf bcftools



  
