BootStrap: yum
OSVersion: 7
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum

%labels
  AUTHOR nicolas.soirat@etu.umontpellier.fr

%post
  echo "Updating CentOS and installing mandatory packages"
  yum -y update 
  yum group install -y "development tools"
  yum -y install  wget git zlib-devel which 
  #Pour Python 3.6.5  
  yum install -y bzip2-devel ncurses-devel readline-devel tk-devel gdbm-devel xz-devel expat-devel 

  echo "Installing the lastest release of Python"
  wget http://python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
  tar xf Python-3.6.3.tar.xz
  cd Python-3.6.3
  ./configure --prefix=/usr/local --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
  make && make altinstall

  echo "Insalling BCFtools"
  git clone git://github.com/samtools/htslib.git
  git clone git://github.com/samtools/bcftools.git
  cd bcftools 
  make
  mv bcftools /usr/local/bin
  cd ..
  rm -rf bcftools

  echo "Installing GATK4"
  wget -O GenomeAnalysisTK-3.8-0.tar.bz2 "https://software.broadinstitute.org/gatk/download/auth?package=GATK"
  tar -xjf GenomeAnalysisTK-3.8.0.tar.bz2
  mkdir /softs
  mv ./GenomeAnalysisTK-3.8-0-ge9d806836/GenomeAnalysisTK.jar /softs/GenomeAnalysisTK/3.8.0/
  rm GenomeAnalysisTK-3.8-0.tar.bz2
  rm -rf ./GenomeAnalysisTK-3.8-0-ge9d806836/ 

  echo "Installing Oracle's java..."
  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.rpm"
  yum localinstall -y jdk-8u151-linux-x64.rpm
  rm jdk-8u151-linux-x64.rpm



  
