#!/bin/bash
tmpDir=$(
  set -e
  cd /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution
  tmpDir="$(mkdir -p "/home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/tmp.819470f1" && echo "/home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/tmp.819470f1")"
  echo "$tmpDir"
)
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME$HOME"
(
cd /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution

)
(
cd /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution


/usr/local/bin/bwa \ /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/inputs/usr/local/share/refData/genome/hg19/hg19.fa \ /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/inputs/usr/local/share/refData/examples/MiniFastqTest_R1.fastq.gz \ /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/inputs/usr/local/share/refData/examples/MiniFastqTest_R2.fastq.gz | /usr/local/bin/samtools \ -o "/home/nsoirat/wdl_test/outpout/sample_test/sample_test.bam"
)  > >(tee '/home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution/stdout') 2> >(tee '/home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution/stderr' >&2)
echo $? > /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution/rc.tmp
(
cd /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution
sync


)
mv /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution/rc.tmp /home/nsoirat/wdl_test/cromwell-executions/wdltest/88657d0f-065a-410f-80d5-a7fdfa334789/call-bwaSamtools/execution/rc
